### ISSUE TITLE
Merge Pull Requests and close resolved Issues

### ISSUE THREAD

**Issue by jkhadley** [riya-17/Neural-Artistic-Style-Transfer#13]
Hey, I have some experience with Neural Nets and would like to contribute to this project. However, It seems like this project has gone stale and I'm not exactly sure as to what is being worked on and what I could start to work on.

**Comment by riya-17** [comment]
@jkhadley I am glad you want to contribute to this project. I am sorry i was busy with some important work. This project is accepting any new innovative ideas and there were some issues introduced by other contributors like speed of the project and GUI.

**Comment by jkhadley** [comment]
Not a problem! I'll start to comment on some of the other issues.
