### ISSUE TITLE
Assertion Error when loading VGG model

### ISSUE THREAD

**Issue by IbrarYunus** [riya-17/Neural-Artistic-Style-Transfer#3]
Hi, I am getting the following error when trying to load the VGG model. 
My imagenet-vgg-verydeep-19.mat file is 510 Megabytes. 

The exact error is as follows: 

![image](https://user-images.githubusercontent.com/11009718/46026763-1740cf80-c0e4-11e8-9134-5c97877b3997.png)

My IDE/System details are: 
PyCharm 2017.3 - Python 3.6
Scipy 1.1.0
Tensorflow 1.10.0
Numpy 1.15.0

Windows 10 64bit

**Comment by riya-17** [comment]
@IbrarYunus Is the path for imagenet correct?

**Comment by IbrarYunus** [comment]
The path seems to be correct (the model is placed in the project directory and path does not have any back-slashes or forward-slashes). 
After the vgg model is loaded from the file, len(vgg) returns 5. Is that the same for you?

**Comment by riya-17** [comment]
@IbrarYunus No, it returns 22. I am not able tounderstand what this error is about but as soon as I get I will surely inform. If you found out you  too please do inform. Until that time i will keep trying :)

**Comment by riya-17** [comment]
Ok.. @IbrarYunus did you find the older version convenient?

**Comment by IbrarYunus** [comment]
Hi, @riya-17 .. Unfortunately no. I am getting the same error. 
Could you show me the MD5 checksum of your code? and the versions of numpy and other modules used?

**Comment by riya-17** [comment]
@IbrarYunus yaa sure

**Comment by riya-17** [comment]
@IbrarYunus  you can find the solution for Assertion Error here : https://github.com/log0/neural-style-painting/issues/2  It should solve the problem. If the problem still prevails than please inform :)

**Comment by IbrarYunus** [comment]
@riya-17  Thanks for the link. :) 
I got it working with this version of [imagenet-vgg-verydeep-19.mat](https://drive.google.com/file/d/0B8QJdgMvQDrVU2cyZjFKU1RrLUU/view?usp=sharing)

**Comment by riya-17** [comment]
@IbrarYunus 👍
